## Numpy Functions

In [2]:
import numpy as np

In [22]:
arr=np.array((34,45,67,89))

In [24]:
arr

array([34, 45, 67, 89])

In [26]:
print(arr)

[34 45 67 89]


In [20]:
np.__version__

'1.26.4'

In [28]:
arr.sum()

235

In [30]:
arr=np.array((34,45,67,8))

In [32]:
arr.sum()

154

In [34]:
arr.dtype

dtype('int32')

### Dimensions in numpy array

In [37]:
a=np.array(45)

In [39]:
b=np.array((45,65))

In [41]:
c=np.array(((45,60),(78,90)))

In [53]:
a.ndim

0

In [55]:
c.ndim

2

In [61]:
b.ndim

1

In [63]:
d=np.array(((45,60),(78,90)))

In [65]:
print(a)

45


In [69]:
print(b)

[45 65]


In [71]:
print(c)

[[45 60]
 [78 90]]


In [73]:
print(b)

[45 65]


### Array Indexing in Numpy

In [78]:
b[0]

45

In [80]:
c[1]

array([78, 90])

In [82]:
c[0][1]

60

In [96]:
z=np.array(([43,56,81,90,102,40],[41,54,80,99,98,97]))

In [92]:
z[5]

40

In [98]:
z[1 , 3]

99

In [102]:
z[1,-2]

98

In [104]:
z[0,1:3]

array([56, 81])

In [106]:
y=np.array([41,54,80,99,98,97])

In [108]:
y[0]

41

In [110]:
y[5]

97

In [112]:
y[1:5]

array([54, 80, 99, 98])

In [116]:
y[1:6:3]

array([54, 98])

## Data Types Numpy

In [120]:
y.dtype

dtype('int32')

In [122]:
x=y=np.array([41.5,54.6,80,99,98.6])

In [124]:
x.dtype

dtype('float64')

In [136]:
y=np.array([1+2j,5+3j,6+4j] ,dtype='complex')

In [138]:
y

array([1.+2.j, 5.+3.j, 6.+4.j])

In [140]:
y.dtype

dtype('complex128')

In [162]:
k=np.array([41.5,54.6,80,99,9755689],dtype='S')

In [164]:
k.dtype

dtype('S7')

In [154]:
k

array([b'41.5', b'54.6', b'80', b'99', b'97'], dtype='|S4')

In [175]:
ab=np.array(['abc','apple','ball'])

In [177]:
ab

array(['abc', 'apple', 'ball'], dtype='<U5')

In [179]:
print(ab)

['abc' 'apple' 'ball']


### Copy

In [171]:
te=x.copy()

In [173]:
te

array([41.5, 54.6, 80. , 99. , 98.6])

In [187]:
te[4]=56

In [189]:
te

array([41.5, 54.6, 80. , 99. , 56. ])

In [191]:
x

array([41.5, 54.6, 80. , 99. , 98.6])

In [193]:
cd=x.view()

In [195]:
cd

array([41.5, 54.6, 80. , 99. , 98.6])

In [197]:
te

array([41.5, 54.6, 80. , 99. , 56. ])

In [199]:
x

array([41.5, 54.6, 80. , 99. , 98.6])

In [201]:
cd[0]=20

In [203]:
cd

array([20. , 54.6, 80. , 99. , 98.6])

In [205]:
x

array([20. , 54.6, 80. , 99. , 98.6])

## Shape

In [208]:
x.shape

(5,)

In [210]:
z=np.array(([43,56,81,90,102,40],[41,54,80,99,98,97]))

In [214]:
z.shape

(2, 6)

In [216]:
print(z)

[[ 43  56  81  90 102  40]
 [ 41  54  80  99  98  97]]


In [220]:
d=np.array((((45,60),(78,90)),((40,40),(80,80))))

In [222]:
d.ndim

3

In [224]:
print(d)

[[[45 60]
  [78 90]]

 [[40 40]
  [80 80]]]


In [226]:
d.shape

(2, 2, 2)

In [235]:
z=z.reshape(4,3)

### Array Iteration

In [237]:
for x in z:
    print(x)

[43 56 81]
[ 90 102  40]
[41 54 80]
[99 98 97]


In [239]:
for a in x:
    print(a)

99
98
97


In [249]:
for x in z:
    l=len(x)
    for i in range(l):
        for j in range(0,l-1):
            print(z[i][j])

43
56
90
102
41
54
43
56
90
102
41
54
43
56
90
102
41
54
43
56
90
102
41
54


In [251]:
for a in x:
    print(a)

99
98
97


### Array Join

In [254]:
ad=np.array([45,55,66,89])

In [256]:
dc=np.array([54,78,90,99])

In [258]:
ad+dc

array([ 99, 133, 156, 188])

In [269]:
np.concatenate((ad,dc))

array([45, 55, 66, 89, 54, 78, 90, 99])

In [262]:
np.vstack((ad,dc))

array([[45, 55, 66, 89],
       [54, 78, 90, 99]])

In [264]:
np.hstack((ad,dc))

array([45, 55, 66, 89, 54, 78, 90, 99])

In [266]:
np.dstack((ad,dc))

array([[[45, 54],
        [55, 78],
        [66, 90],
        [89, 99]]])

### Split

In [275]:
np.array_split(ad ,4)

[array([45]), array([55]), array([66]), array([89])]

In [279]:
ac=np.array(([45,56],[70,90],[60,55],[43,45],[23,22]))

In [293]:
np.hsplit(ad ,4)

[array([45]), array([55]), array([66]), array([89])]

In [299]:
np.hsplit(ac ,2)

[array([[45],
        [70],
        [60],
        [43],
        [23]]),
 array([[56],
        [90],
        [55],
        [45],
        [22]])]

In [301]:
print(ac)

[[45 56]
 [70 90]
 [60 55]
 [43 45]
 [23 22]]


## Numpy Search

In [304]:
np.where(ac==56)

(array([0], dtype=int64), array([1], dtype=int64))

## Sort